name: Version Bump

on: workflow_dispatch

permissions:
  contents: write

jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Deno (latest)
        uses: denoland/setup-deno@v2

      - name: Run @deno/bump-workspaces
        run: |
          git fetch --unshallow origin
          deno task script:bump-versions
        env:
          GITHUB_TOKEN: ${{ secrets.ESERSTACK_PAT }}
          GIT_USER_NAME: ${{ github.actor }}
          GIT_USER_EMAIL: ${{ github.actor }}@users.noreply.github.com
